name: event_mgm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  loop_page_view: ^1.2.5
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/